# Netlify 빌드 및 리디렉션 설정

[build]
  # 빌드 명령을 실행할 기본 디렉토리
  base    = "frontend"
  
  # Next.js 프로젝트의 빌드 명령어
  command = "next build"
  
  # 빌드 결과물이 생성되는 디렉토리 (저장소 루트 기준)
  publish = "out"

# 모든 요청을 Next.js가 처리하도록 하는 리디렉션 규칙
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200